spring:
  config:
    activate:
      on-profile: dev
    import: database-secrets.yml
  data:
    mongodb:
      host: ${mongodb-connection.host}
      port: ${mongodb-connection.port}
      database: ${mongodb-connection.database}
