spring:
  config:
    activate:
      on-profile: default
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:pocket_pharmacy
    username: test_user
    password: 12345
    driverClassName: org.h2.Driver
