spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:pocket_pharmacy
    username: test-user
    password: 12345
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
